project:
  type: website
  output-dir: docs

website:
  title: "The WAL Street Journal"
  google-analytics: G-CKDPXJ4Y38
  navbar:
    right:
      - icon: github
        href: https://github.com/thewalstreetjournal
      - icon: youtube
        href: https://www.youtube.com/@TheWALStreetJournal
    left:
      - href: index.qmd
        text: Blog
      - href: about.qmd
        text: About
        
format:
  html:
    theme: 
      light: flatly
      dark: darkly 
    css: styles.css
    toc: true
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Sofia&family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
    include-after-body: 
      text: | 
        <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-python.min.js"></script>


